### ISSUE TITLE
When Device location is 'off'  ,  "Enable Location"  button isn't working  - ios App v1.0.1 issue 

### ISSUE THREAD

**Issue by ShreyaaSahu** [Path-Check/covid-safe-paths#717] opened 2020-04-29 06:36 UTC
## Version

- Type of phone:  iPhone
- OS Version: ios 13.3
- Model: iPhone XR

## Steps to reproduce

1. Device location is set to "off" .

2. launch  COVID SafePath app
3. Click on "Get Started"
4. Accept the Licensing agreement 
5. Cross the 3 onboarding screen 
6. Next Screen will be " Location access " and "Allow notifications " options.
7. clicking on "Enable Location"  button at bottom  - isn't working 
8  After clicking "Skip the step"
9. Next screen will be "Enable notifications ".
 

## Expected Behavior

"Enable Location"  button working

![IMG-4629](https://user-images.githubusercontent.com/64080646/80566977-c73d9380-8a11-11ea-8615-78fd21334183.PNG)
![IMG-4630](https://user-images.githubusercontent.com/64080646/80566984-ca388400-8a11-11ea-89f5-f4ea9afc4809.PNG)

**Comment by Krish023** [comment] 2020-04-29 13:16
Can you please assign it to me. I will look at this issue.

**Comment by Krish023** [comment] 2020-04-29 14:54
Hi @ShreyaaSahu Can you please verify on ANdroid also?

**Comment by diarmidmackenzie** [comment] 2020-05-02 18:04
This problem does not exist in Android.  In Android there is a different problem - if location settings are "off" on the device, the app allows location services to be set up & reports them all as working.  But in fact they are not as locaton services are "off".

We should check this out as part of re-testing #719 - I will add a note there.

**Comment by sparks2209** [comment] 2020-05-21 09:09
Please assign this to me

**Comment by sparks2209** [comment] 2020-05-21 12:02
We have four kind of cases for location permission
    UNAVAILABLE,
    DENIED,
    BLOCKED,
    GRANTED
and 3 states for location permission(UNKNOWN, Granted, Blocked).

In app we are managing only two cases with 2 states(Granted and Blocked), we have a state called UNKNOWN which is not managed in app.

In this specific scenario we have UNAVAILABLE case from location permission, i would like to ask what will be expected behaviour? 
Does app continues to next state i.e notification permission and updating location permission state to UNKNOWN.

What will happen in case of location service denied as we are not handling this case.

**Comment by summetj** [comment] 2020-05-21 23:32
Suggest you ask in #app_dev for expected behavior.

**Comment by sparks2209** [comment] 2020-05-26 06:17
Couldn't resolve this issue due to blockers
https://github.com/Path-Check/covid-safe-paths/issues/890
https://github.com/Path-Check/covid-safe-paths/issues/911

Once above issues are resolved, i can commit changes to Onboadring5 file to resolve this issue.

**Comment by sparks2209** [comment] 2020-06-01 04:19
We can close this issue as it's not happening

**Closed** 2020-06-01 19:03 UTC
Labels: ios
