### ISSUE TITLE
Infected person will get notifications for all the days after their data is released

### ISSUE THREAD

**Issue by tremblerz** [Path-Check/covid-safe-paths#509] opened 2020-04-14 08:14 UTC
Infected person will get notifications for all the days after their data is released since they are intersecting with themselves all the time in the location history.

**Comment by diarmidmackenzie** [comment] 2020-04-14 19:23
I think we have logic to calculate how long the user spent in contact with another user?

That logic presumably works even if both users are moving around?

If so, then I think that logic ought to compute a 336 hour continuous contact.  It ought to be possible to spot that and drop it out of the report?

That said, it's not obvious to me that a diagnosed user will use the app beyond pushing their local data.  If they do use it, they would want different things from it from an undiagnosed user...  If we do drop their data, and they don't cross paths with anyone else, it might not be appropriate to broadcast them a "green" status either....

**Comment by diarmidmackenzie** [comment] 2020-04-15 05:21
I've realized that data redaction that may have been applied to the public data set means we can't rely on matching the trail 100%.

**Comment by diarmidmackenzie** [comment] 2020-04-15 05:27
Will this actually be an ongoing problem?

One you are diagnosed, upload your data and work the the HA on redaction and publication, do you go on pulishing further location data?

My guess is that at that point you sel-isolate at home, having minimal contact with anyone, and no longer moving around the community.

And therefore there would be no value in pushing further data about your movements up to the HA.

So this will be a one-off issue when your dataset is published, rather than a permanent issue.

It actually provides a means for the user to (a) notice when their data goes public and (b) have confidence that the redaction they had requested was actually implemented correctly.

With some appropriate direction for the user, this could be seen as a feature, not a bug.

**Comment by Mr-EZG** [comment] 2020-04-18 06:17
On this topic, maybe we can introduce a counter variable per application? Or boolean to essentially mark the user as infected and not send them notifications for 14-20 days after marking when they were diagnosed? Or rather send notifications to ask if/when they recovered? (To potentially apply an automatic or manual reset to "healthy") However, continue their option to share their data as before? That way they can continue share their information with others in case they might be healthy enough to stay home, but might need to venture out to buy groceries, etc. if having nobody around to help them out.

The idea behind making the user as "healthy" eventually again might be a useful feature as there are some cases of catching the virus again after recovering from it.

On a more general thought: This could lead to three potential options that might be worth asking the user and be very effective when asking in different times?

Options when starting:
1. Giving permission for automatic uploading (and uploading when possible with wifi, by choice, etc.)
2. Never upload data without express permission (and mention that these settings can be changed later)

Options if diagnosed (Pop up again):
1. Giving permission for one time data upload (of information up to this point)
2. Giving permission for or automatic uploading (if not already done)
3. Not upload data

Reasoning:
This will allow the user to use the app without compromising the premise of not sharing their data without their permission, but also allow for more convenience to share their information. The user might also have a change in heart if diagnosed and be more willing to share their data for the sake of others. But the idea of "1 time pop-ups" adds convenience and makes it more likely for the everyday person to share their data.

This could also be nice as we would generally be more interested in the paths of affected people. (Even though it would be better to also have non-infected paths since there is a gap for when the user was contagious and crossing other user's path vs getting diagnosed)

I would be more than happy to continue discussing this and/or working to help implement these or other ideas with others.

**Comment by summetj** [comment] 2020-05-01 16:08
@tremblerz  - Is this still an issue we need to track/assign to someone, or should it be closed?

**Comment by Patrick-Erichsen** [comment] 2020-05-22 17:49
Closing this issue out as we have taken it into consideration and documented the feedback on [this page in Jira](https://pathcheck.atlassian.net/wiki/spaces/SAFE/pages/81265028/GitHub+Issues+-+Community+Feature+Requests).

**Closed by Patrick-Erichsen** 2020-05-22 17:49 UTC
Labels: question
