### ISSUE TITLE
News does not load up on the first time sometimes

### ISSUE THREAD

**Issue by tremblerz** [Path-Check/covid-safe-paths#615] opened 2020-04-21 19:42 UTC
## Version

- Model: iPhone 6s iOS 13.4

## Steps to reproduce

Reproducing is a bit inconsistent but it has happened sufficient number of times to assume the bug does exist.
Install the app, go to the latest news
It just remains stuck on loading
Press back and go to the latest news again
This time it loads up right away

## Expected Behavior

The News should get loaded in the first pass and shouldn't require going back and coming into it again.

**Comment by saranyaharidas** [comment] 2020-04-22 05:31
will check this one

**Comment by summetj** [comment] 2020-05-04 11:19
@saranyaharidas - Are you still working on this issue?

**Comment by jincepgeorge** [comment] 2020-05-05 07:06
I have just looked this issue but unable reproduce. However I suspect the issue might be because the carousel and webviews are rendering at the same time. So I have added a few milliseconds delay to load the carousel and found the transition to news screen is also smoother in android and loading the news contents properly in both platforms . If this is an acceptable solution I can raise a PR.

**Comment by summetj** [comment] 2020-05-05 17:27
> I have just looked this issue but unable reproduce. However I suspect the issue might be because the carousel and webviews are rendering at the same time. So I have added a few milliseconds delay to load the carousel and found the transition to news screen is also smoother in android and loading the news contents properly in both platforms . If this is an acceptable solution I can raise a PR.

I hesitate to make a change to the codebase for an issue that may not currently exist (or at least can't be reproduced)....on the other hand, a few ms delay shouldn't cause other issues (famous last words).... If you can quantify the "smoother" transition and feel it is an improvement we could certainly consider a PR.

**Comment by Patrick-Erichsen** [comment] 2020-05-22 18:15
Closing as we have work in-flight to refactor the News screen.

**Closed by Patrick-Erichsen** 2020-05-22 18:15 UTC
