### ISSUE TITLE
FEATURE REQ: Prediction of regionwise COVID cases based on the data from confirmed cases and self reported cases

### ISSUE THREAD

**Issue by tremblerz** [Path-Check/covid-safe-paths#306] opened 2020-04-01 15:35 UTC
Utilize both encrypted and redacted data for predicting regionwise COVID cases.

**Comment by penrods** [comment] 2020-04-01 17:28
I think this is likely also a Healthcare Authority operation, not really an app-side feature.  Do you agree?

**Comment by E3V3A** [comment] 2020-04-02 11:54
I think it would be very useful and fairly easy to implement. I'm of the opinion that we should try to release the strain and expectations of any health "authority", as much as possible. In addition, (clearly?) not all health authorities have the possibility and time to implement this right now.

**Comment by andreanuzzo** [comment] 2020-04-04 02:11
Strongly disagree, again. We don't have a team of epidemiologist and physicians to validate those data. 

Confirmed cases are biased by the people who reach the healthcare providers (especially in the US, not 100%) and those who are tested (again, not 100%) and doesn't track asymptomatic and presymptomatic which are still contagious (to a percentage yet unknown) and thus generate contacts.

Would not implement in the app.

**Comment by E3V3A** [comment] 2020-04-05 00:28
@andreanuzzo 

I think the issue is in the title "prediction". If we skip that word, it would be very useful to have a heat-map like picture over your own city or neighborhood. I completely agree that we should not have to employ any epidemiologist for this. But I do see the important advantage of being able to self-report, especially as there are now thousands of PoC kits being sold online for people to test themselves at home. They need a way to self-report.  (Like I mentioned in #309.) 

NOTE. Those the anti-body kits are far better to help determine and detect otherwise the large pool of unknown cases. However, they are not directly telling you if you are contagious, unless you have stayed home AND been well in the last 3 weeks.

**Comment by Patrick-Erichsen** [comment] 2020-05-22 17:12
Closing this issue out as we have taken it into consideration and documented the feedback on [this page in Jira](https://pathcheck.atlassian.net/wiki/spaces/SAFE/pages/81265028/GitHub+Issues+-+Community+Feature+Requests).

**Closed by Patrick-Erichsen** 2020-05-22 17:12 UTC
Labels: Data Science
