### ISSUE TITLE
Android 8.1 not working

### ISSUE THREAD

**Issue by tremblerz** [Path-Check/covid-safe-paths#113] opened 2020-03-19 20:50 UTC

**Comment by harshvitra** [comment] 2020-03-25 23:34
Hey, I just checked it works in Android 8.1

Was the issue for a specific device ?

**Comment by rparet** [comment] 2020-03-29 14:33
@tremblerz some more context here? perhaps this is now working again or is device specific?

**Comment by tstirrat** [comment] 2020-05-22 00:34
Closing, not able to reproduce on a 8.1 emulator. Reopen with device specifics if you can reproduce.

**Closed by tstirrat** 2020-05-22 00:34 UTC
Labels: Bug, For next release, good first issue, help wanted
